### ISSUE TITLE
First call to pinMode(pin, ANALOG_OUTPUT) sets output high momentarily. 

### ISSUE THREAD

**Issue by raphael-bmec-co** [sparkfun/SX1509_IO-Expander#6]
The first call to `pinMode(pin, ANALOG_OUTPUT)` after `begin()` causes that pin to go high momentarily.

### Details
To avoid setting analog pins into an unknown state. We always call `analogWrite(pin, output)` before calling `pinMode(pin, ANALOG_OUTPUT)`. However, as above, on the first call to `pinMode(pin, ANALOG_OUTPUT)` the pin is momentarily set high before going to `output`.

We have worked around this by making a call `pinMode(unusedPin, ANALOG_OUTPUT)'. Obviously this would be problematic if we didn't have any unused pins.

**Comment by nseidle** [comment]
Line numbers are always helpful. Did you know you can [link to them](https://github.com/sparkfun/SparkFun_SX1509_Arduino_Library/blob/master/examples/analogWrite/analogWrite.ino#L63)? I assume you're talking about the analogWrite example but let me know.

So what you're recommending is putting a `io.analogWrite(SX1509_LED_PIN, 0);` before [line 63](https://github.com/sparkfun/SparkFun_SX1509_Arduino_Library/blob/master/examples/analogWrite/analogWrite.ino#L63)?

Also note: This repo is for the hardware (PCB). The library is over [here](https://github.com/sparkfun/SparkFun_SX1509_Arduino_Library) and this issue is a library issue, not a hardware issue. It's our fault. This repo is old and dates to a time when to smashed the two together. I've removed the library from this repo to avoid future confusion.

**Comment by raphael-bmec-co** [comment]
Thanks for the hint on linking to line numbers.

However, I am not talking about the analogWrite example. After initialising the chip, the first call to `pinMode(pin, ANALOG_OUTPUT)` from anywhere in any code causes said `pin` to be momentarily set high. There is some kind of bug that is causing the pin to be pulled up when the pin mode is set to analog. But this only occurs for the first call to `pinMode`. There must be some additional register configuration taking place on the first call or something? Let me know if you need further clarificaiton.

Would you like me to open this issue and move this conversation to the library repo?

**Comment by nseidle** [comment]
No need to move issues, we'll try to get it finished here. 

![image](https://user-images.githubusercontent.com/117102/151627934-ce6265f1-574b-40fb-9c3b-5b8c5fe1a715.png)

pinMode has an initial level setting that is default high. Try a `pinMode(pin, ANALOG_OUTPUT, LOW)` and let me know if you still have the issue.

**Comment by raphael-bmec-co** [comment]
Ahhhh! Thanks @nseidle. Much appreciated.
